version: '3.3'
services:
  school:
    container_name: school
    build: .
    ports:
      - "5001:5001"

  contacts:
    container_name: contacts
    build: ./contacts
    ports:
      - "5000:5000"
    networks:
      - contacts
networks:
  contacts: